[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor]
line-number = "relative"
text-width = 80
cursorline = true
color-modes = true
idle-timeout = 100
# end-of-line-diagnostics = "hint"

[editor.cursor-shape]
select = "underline"

# [editor.inline-diagnostics]
# cursor-line = "warning"
