## ------ LSPs ------

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[language-server.rust-analyzer.config.check]
command = "clippy"

## ------ Languages ------

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
